/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PositionSlugRouteImport } from './routes/position.$slug'
import { Route as PlayerIdRouteImport } from './routes/player.$id'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as LeagueIdRouteImport } from './routes/league.$id'

const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionSlugRoute = PositionSlugRouteImport.update({
  id: '/position/$slug',
  path: '/position/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdRoute = PlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueIdRoute = LeagueIdRouteImport.update({
  id: '/league/$id',
  path: '/league/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/players': typeof PlayersRoute
  '/league/$id': typeof LeagueIdRoute
  '/match/$id': typeof MatchIdRoute
  '/player/$id': typeof PlayerIdRoute
  '/position/$slug': typeof PositionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/players': typeof PlayersRoute
  '/league/$id': typeof LeagueIdRoute
  '/match/$id': typeof MatchIdRoute
  '/player/$id': typeof PlayerIdRoute
  '/position/$slug': typeof PositionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/players': typeof PlayersRoute
  '/league/$id': typeof LeagueIdRoute
  '/match/$id': typeof MatchIdRoute
  '/player/$id': typeof PlayerIdRoute
  '/position/$slug': typeof PositionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/players'
    | '/league/$id'
    | '/match/$id'
    | '/player/$id'
    | '/position/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/players'
    | '/league/$id'
    | '/match/$id'
    | '/player/$id'
    | '/position/$slug'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/players'
    | '/league/$id'
    | '/match/$id'
    | '/player/$id'
    | '/position/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  PlayersRoute: typeof PlayersRoute
  LeagueIdRoute: typeof LeagueIdRoute
  MatchIdRoute: typeof MatchIdRoute
  PlayerIdRoute: typeof PlayerIdRoute
  PositionSlugRoute: typeof PositionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position/$slug': {
      id: '/position/$slug'
      path: '/position/$slug'
      fullPath: '/position/$slug'
      preLoaderRoute: typeof PositionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id': {
      id: '/player/$id'
      path: '/player/$id'
      fullPath: '/player/$id'
      preLoaderRoute: typeof PlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$id': {
      id: '/league/$id'
      path: '/league/$id'
      fullPath: '/league/$id'
      preLoaderRoute: typeof LeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  PlayersRoute: PlayersRoute,
  LeagueIdRoute: LeagueIdRoute,
  MatchIdRoute: MatchIdRoute,
  PlayerIdRoute: PlayerIdRoute,
  PositionSlugRoute: PositionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
